line-length = 80
target-version = "py310"

[lint]
select = ["ALL"]

ignore = [
    "ANN",    # Skip type annotation guidelines
    "D",      # Skip docstring guidelines
    "COM812", # Skip Trailing commas
]

[lint.per-file-ignores]
"tests/*" = [
    "PLR2004", # Allow magic numbers in tests
    "S101",    # Allow assert statements in tests
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true

[lint.isort]
split-on-trailing-comma = false
